import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';

dotenv.config();

const supabaseUrl = process.env.SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_KEY;
const supabase = createClient(supabaseUrl, supabaseKey);

// =========================================================================
// SALINAN DATA DARI FAMILY-DATA.JS KAMU
// =========================================================================
const familyData = [
    {
        id: 1,
        firstName: "Hernandez",
        lastName: "Riverra",
        gender: "male",
        role: "The First Governor",
        generation: 1,
        status: "Deceased",
        photo: "",
        biography:
          "Pondasi utama dinasti yang meyakini bahwa hukum tertulis hanyalah lembaran rapuh tanpa topangan kekuatan militer. Mengorbankan kedamaian masa mudanya demi mendirikan kedaulatan absolut dari balik meja besi birokrasi pemerintahan.",
        occupation: "Ex-Governor of San Andreas",
        father: null,
        mother: null,
        spouse: 2,
        children: [10, 12, 14, 16, 18],
      },
      {
        id: 2,
        firstName: "Charleta",
        lastName: "Valence",
        gender: "female",
        role: "The Silent Anchor",
        generation: 1,
        status: "Deceased",
        photo: "",
        biography:
          "Pena penyeimbang di balik kejamnya ambisi sang pendiri. Charleta mengajarkan bahwa emas setinggi gunung tidak akan pernah mampu membasuh noda kutukan jika darah saudara sendiri dikorbankan demi kekuasaan.",
        occupation: "Founder of Riverra Philanthropic Trust",
        father: null,
        mother: null,
        spouse: 1,
        children: [10, 12, 14, 16, 18],
      },
    
      /* =======================================================
             GENERATION II (The Architects - Deceased)
          ======================================================= */
      {
        id: 10,
        firstName: "Fernando",
        lastName: "Riverra",
        gender: "male",
        role: "Justice Keeper",
        generation: 2,
        status: "Deceased",
        photo: "",
        biography:
          "Menghabiskan seluruh helaan napasnya di bawah sumpah suci meja pengadilan. Baginya, keadilan di kota ini adalah komoditas mahal, dan dinasti Riverra wajib memegang palu ketukan tertingginya.",
        occupation: "Chief Justice of San Andreas Supreme Court",
        father: 1,
        mother: 2,
        spouse: 11,
        children: [21, 23],
      },
      {
        id: 11,
        firstName: "Zhao",
        lastName: "Lusi",
        gender: "female",
        role: "Diplomat Force",
        generation: 2,
        status: "Deceased",
        photo: "",
        biography:
          "Darah Asia yang menyuntikkan ketenangan taktis ke dalam lingkar kekuasaan barat. Memegang teguh prinsip bahwa musuh paling mematikan bukanlah penembak jitu, melainkan mereka yang tersenyum manis di meja negosiasi.",
        occupation: "State Secretary of Government Affairs",
        father: null,
        mother: null,
        spouse: 10,
        children: [21, 23],
      },
      {
        id: 12,
        firstName: "Gerrald",
        lastName: "Riverra",
        gender: "male",
        role: "Iron Fist PD",
        generation: 2,
        status: "Deceased",
        photo: "",
        biography:
          "Legenda penegak hukum tanpa kompromi yang mendiktekan lencana besi kepada para anggotanya. Menanamkan doktrin bawah ketertiban kota hanya tercapai saat kriminal lebih takut pada polisi dibanding kematian.",
        occupation: "Police Commissioner - LSPD High Command",
        father: 1,
        mother: 2,
        spouse: 13,
        children: [24, 26],
      },
      {
        id: 13,
        firstName: "Alexandra",
        lastName: "Kowalski",
        gender: "female",
        role: "Tactical Brain",
        generation: 2,
        status: "Deceased",
        photo: "",
        biography:
          "Arsitek taktis di balik barisan penyerangan perimeter zona merah. Memiliki keyakinan mutlak bahwa kekuatan senjata tanpa strategi matang hanyalah cara bodoh memesan tempat di kamar mayat.",
        occupation: "Tactical Commander - SWAT Division",
        father: null,
        mother: null,
        spouse: 12,
        children: [24, 26],
      },
      {
        id: 14,
        firstName: "Vettel",
        lastName: "Riverra",
        gender: "male",
        role: "Intelligence Shadow",
        generation: 2,
        status: "Deceased",
        photo: "",
        biography:
          "Memilih terkubur di dalam kegelapan agar cahaya kota tetap bersinar terang. Baginya, informasi adalah mata uang tertinggi; siapa yang menggenggam rahasia kota, dia memegang takdir seluruh jiwa di dalamnya.",
        occupation: "Director of Intelligence - IAA Division",
        father: 1,
        mother: 2,
        spouse: 15,
        children: [28],
      },
      {
        id: 15,
        firstName: "Kelly",
        lastName: "Sanders",
        gender: "female",
        role: "Shadow Operator",
        generation: 2,
        status: "Deceased",
        photo: "",
        biography:
          "Analis kriptografi berdarah dingin yang mampu meruntuhkan jaringan kartel transnasional hanya lewat jajaran baris kode enkripsi dari balik monitor terselubung.",
        occupation: "Chief Cyber Security Specialist - Government",
        father: null,
        mother: null,
        spouse: 14,
        children: [28],
      },
      {
        id: 16,
        firstName: "Carlos",
        lastName: "Riverra",
        gender: "male",
        role: "Lifesaver Shield",
        generation: 2,
        status: "Deceased",
        photo: "",
        biography:
          "Di tengah gempuran ego faksi dan desing peluru panas, Carlos memilih merawat kemanusiaan. Menggenggam prinsip bahwa sedalam apa pun dosa di jalanan, tiap nyawa berhak atas kesempatan kedua di atas meja bedah.",
        occupation: "Chief of Medical Services - EMS Command",
        father: 1,
        mother: 2,
        spouse: 17,
        children: [30, 32],
      },
      {
        id: 17,
        firstName: "Hanabi",
        lastName: "Nakamura",
        gender: "female",
        role: "Guardian Angel",
        generation: 2,
        status: "Deceased",
        photo: "",
        biography:
          "Satu-satunya malaikat pelindung yang berani menembus hujan tembakan demi menyeret personil yang tumbang. Dedikasi medismya melampaui batas ego seragam birokrasi.",
        occupation: "Senior Trauma Surgeon Specialist - EMS",
        father: null,
        mother: null,
        spouse: 16,
        children: [30, 32],
      },
      {
        id: 18,
        firstName: "Sebastian L.",
        lastName: "Riverra",
        gender: "male",
        role: "The White Collar",
        generation: 2,
        status: "Deceased",
        photo: "",
        biography:
          "Memutar poros ekonomi kota dari gemerlap distrik hiburan malam. Memiliki filosofi: 'Uang memang tidak bisa membeli kesetiaan murni, namun uang mampu mendanai peluru untuk melenyapkan sang pengkhianat.'",
        occupation: "Managing Director - Diamond Casino & Resort",
        father: 1,
        mother: 2,
        spouse: 19,
        children: [33],
      },
      {
        id: 19,
        firstName: "Naomi",
        lastName: "Hakanatomi",
        gender: "female",
        role: "Luxury Monarch",
        generation: 2,
        status: "Deceased",
        photo: "",
        biography:
          "Putri sindikat timur jauh yang berhasil meleburkan rantai suplai pasar gelap menjadi imperium logistik legal yang tak tersentuh oleh radar audit kepolisian.",
        occupation: "Chief Executive Officer - Luxury Goods Importer",
        father: null,
        mother: null,
        spouse: 18,
        children: [33],
      },
    
      /* =======================================================
             GENERATION III (The Inheritors - Deceased)
          ======================================================= */
      {
        id: 20,
        firstName: "Zhou",
        lastName: "Wijaya",
        gender: "male",
        role: "Legal Advisor",
        generation: 3,
        status: "Deceased",
        photo: "",
        biography:
          "Arsitek hukum berdarah dingin yang memandang regulasi negara sebagai instrumen permainan fleksibel. Terkenal karena kemampuannya memanipulasi celah konstitusi demi meloloskan kepentingan dinasti.",
        occupation: "Senior District Attorney - Department of Justice",
        father: null,
        mother: null,
        spouse: 21,
        children: [40, 42],
      },
      {
        id: 21,
        firstName: "Athena",
        lastName: "Riverra",
        gender: "female",
        role: "The Treasury Guard",
        generation: 3,
        status: "Deceased",
        photo: "",
        biography:
          "Pemegang kunci brankas utama sirkulasi anggaran wilayah. Mengadopsi prinsip dasar bahwa kekuasaan sejati tidak pernah lahir dari kursi politik, melainkan dari rantai pasokan aset yang tak pernah putus.",
        occupation: "Chief Treasurer - San Andreas State Treasury",
        father: 10,
        mother: 11,
        spouse: 20,
        children: [40, 42],
      },
      {
        id: 22,
        firstName: "James",
        lastName: "Delcano",
        gender: "male",
        role: "Fleet Commander",
        generation: 3,
        status: "Deceased",
        photo: "",
        biography:
          "Penguasa gerbang pelabuhan yang mendiktekan setiap inci pergerakan impor-ekspor kota. Menghidupi keyakinan filosofis bahwa siapa pun yang mengendalikan jalur logistik, dia yang memegang pasokan napas kota.",
        occupation: "Head Executive - Port & Customs Authority",
        father: null,
        mother: null,
        spouse: 23,
        children: [44, 45, 46],
      },
      {
        id: 23,
        firstName: "Anabella",
        lastName: "Riverra",
        gender: "female",
        role: "Public Figure",
        generation: 3,
        status: "Deceased",
        photo: "",
        biography:
          "Memanfaatkan pengaruh sosial elitnya sebagai tirai pelindung pergerakan internal keluarga. Percaya penuh bahwa citra publik yang sempurna adalah perisai terbaik dari intaian investigasi federal.",
        occupation: "Director of Public Relations - Government",
        father: 10,
        mother: 11,
        spouse: 22,
        children: [44, 45, 46],
      },
      {
        id: 24,
        firstName: "Marc",
        lastName: "Riverra",
        gender: "male",
        role: "Tactical Executioner",
        generation: 3,
        status: "Deceased",
        photo: "",
        biography:
          "Ujung tombak penegakan hukum jalanan yang memimpin garis depan konfrontasi kartel. Mengukir filosofi hidupnya pada laras senapan dinas: 'Kedamaian faksi hanya akan tercipta setelah badai peluru meredam anarki.'",
        occupation: "Police Captain - LSPD High Command",
        father: 12,
        mother: 13,
        spouse: 25,
        children: [47, 48],
      },
      {
        id: 25,
        firstName: "Ailen",
        lastName: "Riverra",
        gender: "female",
        role: "Forensic Master",
        generation: 3,
        status: "Deceased",
        photo: "",
        biography:
          "Membaca pesan sunyi dari mayat dan pola bercak darah untuk merajut mosaik kejahatan. Baginya, seketat apa pun penjahat mengubur rahasia, jasad korban akan selalu berbisik mengungkap kebenaran.",
        occupation: "Director of Forensic Investigation Department",
        father: null,
        mother: null,
        spouse: 24,
        children: [47, 48],
      },
      {
        id: 26,
        firstName: "Arthur",
        lastName: "Riverra",
        gender: "male",
        role: "Highway Warden",
        generation: 3,
        status: "Deceased",
        photo: "",
        biography:
          "Penguasa rute krusial antar-negara bagian yang meredam penyelundupan di wilayah tandus. Percaya bahwa melonggarkan pengawasan perbatasan gurun sama saja dengan mengundang kehancuran masuk ke pusat kota.",
        occupation: "Sheriff Lieutenant - BCSO High Command",
        father: 12,
        mother: 13,
        spouse: 27,
        children: [49, 50],
      },
      {
        id: 27,
        firstName: "Rissa",
        lastName: "Kato",
        gender: "female",
        role: "Dispatch Coordinator",
        generation: 3,
        status: "Deceased",
        photo: "",
        biography:
          "Suara dingin nan tenang di balik jaringan radio komunikasi yang menjadi navigasi hidup dan mati bagi para unit saat terjebak dalam eskalasi baku tembak anarkis.",
        occupation: "Head of Communications - LSPD Dispatch",
        father: null,
        mother: null,
        spouse: 26,
        children: [49, 50],
      },
      {
        id: 28,
        firstName: "Maxxius",
        lastName: "Riverra",
        gender: "male",
        role: "Undercover Agent",
        generation: 3,
        status: "Deceased",
        photo: "",
        biography:
          "Hidup di dalam labirin ribuan identitas palsu demi menyusup ke jantung sindikat mafia. Kehilangan jati diri aslinya demi loyalitas buta pada stabilitas kekuasaan dinasti.",
        occupation: "FIB Special Agent In-Charge - Intelligence Division",
        father: 14,
        mother: 15,
        spouse: 29,
        children: [51, 52, 53],
      },
      {
        id: 29,
        firstName: "Akane",
        lastName: "Kurokawa",
        gender: "female",
        role: "Intel Analyst",
        generation: 3,
        status: "Deceased",
        photo: "",
        biography:
          "Otak taktis di balik layar komando pusat yang membaca pergerakan radar frekuensi gelap dan menyusun peta kekuatan faksi bawah tanah.",
        occupation: "Chief Intelligence Operations - FIB Division",
        father: null,
        mother: null,
        spouse: 28,
        children: [51, 52, 53],
      },
      {
        id: 30,
        firstName: "Miguel",
        lastName: "Riverra",
        gender: "male",
        role: "Medical General",
        generation: 3,
        status: "Deceased",
        photo: "",
        biography:
          "Konseptor utama evakuasi taktis udara saat eskalasi konflik kota memuncak. Dedikasinya melahirkan pemikiran bahwa baling-baling helikopter penyelamat adalah sekat tipis antara mukjizat hidup atau kepulangan dalam peti.",
        occupation: "EMS Deputy Chief - Air Medevac Command",
        father: 16,
        mother: 17,
        spouse: 31,
        children: [
          54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 71, 72,
        ],
      },
      {
        id: 31,
        firstName: "Emmilian",
        lastName: "Hawthorne",
        gender: "female",
        role: "Pharmaceutical Brain",
        generation: 3,
        status: "Deceased",
        photo: "",
        biography:
          "Ilmuwan farmasi yang mendedikasikan hidupnya untuk meriset serum penawar racun dan stimulan taktis guna menjaga kesiapan tempur garda depan penegak hukum.",
        occupation: "Chief Medical Researcher - Department of Health",
        father: null,
        mother: null,
        spouse: 30,
        children: [
          54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 71, 72,
        ],
      },
      {
        id: 32,
        firstName: "Matteo A",
        lastName: "Riverra",
        gender: "male",
        role: "Emergency Logistics Commander",
        generation: 3,
        status: "Deceased",
        photo: "",
        biography:
          "Arsitek utama sistem logistik darurat San Andreas yang membangun jaringan distribusi kendaraan, suplai, dan pusat komando saat bencana maupun krisis berskala besar. Kepemimpinannya memastikan setiap unit di lapangan selalu memiliki dukungan operasional tanpa mengenal waktu.",
        occupation: "Director of Emergency Logistics - State Emergency Management",
        father: 16,
        mother: 17,
        spouse: 33,
        children: [73, 75, 76],
      },
      {
        id: 33,
        firstName: "Valentina",
        lastName: "Serrano",
        gender: "female",
        role: "Forensic Science Pioneer",
        generation: 3,
        status: "Deceased",
        photo: "",
        biography:
          "Pelopor pengembangan laboratorium forensik modern yang memperkenalkan metode identifikasi berbasis DNA dan analisis bukti ilmiah untuk membantu penyelidikan kriminal. Warisannya menjadi fondasi bagi generasi penyidik dan ahli forensik di San Andreas.",
        occupation: "Chief Forensic Scientist - State Crime Laboratory",
        father: null,
        mother: null,
        spouse: 32,
        children: [73, 75, 76],
      },
      {
        id: 34,
        firstName: "Jorge",
        lastName: "Martin",
        gender: "male",
        role: "The Legalizer",
        generation: 3,
        status: "Deceased",
        photo: "",
        biography:
          "Memonopoli tata ruang kota untuk dialihkan menjadi distrik bisnis eksklusif. Prinsipnya tegas: 'Senjata di jalanan hanya membuang darah, namun pena korporasi menyerap kekuasaan tanpa meninggalkan sidik jari.'",
        occupation: "Head of Infrastructure & Urban Development",
        father: null,
        mother: null,
        spouse: 35,
        children: [77, 78, 79],
      },
      {
        id: 35,
        firstName: "Elisa",
        lastName: "Riverra",
        gender: "female",
        role: "Luxury Magnate",
        generation: 3,
        status: "Deceased",
        photo: "",
        biography:
          "Mengendalikan siklus pasar otomotif kelas atas kota. Mengubah kesenangan hedonisme para borjuis menjadi cerobong pencucian aset raksasa yang menyokong finansial pergerakan dinasti.",
        occupation: "Chief Executive Officer - Premium Deluxe Motorsport",
        father: 18,
        mother: 19,
        spouse: 34,
        children: [77, 78, 79],
      },
    
      /* =======================================================
             GENERATION IV (The Living Heirs - Alive)
          ======================================================= */
      {
        id: 40,
        firstName: "Dede",
        lastName: "Anggasta",
        gender: "male",
        generation: 4,
        status: "Alive",
        photo: "",
        biography:
          "Memilih jalur presisi tinggi dengan memimpin unit pengejaran elit. Baginya, kecepatan adalah instrumen kontrol jalanan; siapa yang menguasai aspal, dialah yang mendikte pelarian musuh.",
        occupation: "Police Captain - High Speed Intercept Unit (LSPD)",
        father: 20,
        mother: 21,
        spouse: 41,
        children: [],
      },
      {
        id: 41,
        firstName: "Michele",
        lastName: "Bellini",
        gender: "female",
        generation: 4,
        status: "Alive",
        photo: "",
        biography:
          "Pakar komunikasi visual yang bertugas merestorasi wajah korporasi birokrasi. Mengendalikan opini publik dari balik layar lewat strategi narasi media yang elegan dan persuasif.",
        occupation: "Chief Director - Government Creative Marketing",
        father: null,
        mother: null,
        spouse: 40,
        children: [],
      },
      {
        id: 42,
        firstName: "Nicholas",
        lastName: "Venlie",
        gender: "male",
        generation: 4,
        status: "Alive",
        photo: "",
        biography:
          "Perwira muda ambisius yang bergerak di garis batas bayang-bayang. Bertekad membasuh reputasi kelam nama leluhurnya lewat tumpukan berkas penangkapan sindikat terorganisir.",
        occupation: "Police Sergeant - Intercept Command Unit (LSPD)",
        father: 20,
        mother: 21,
        spouse: 43,
        children: [],
      },
      {
        id: 43,
        firstName: "Zai",
        lastName: "Navarro",
        gender: "female",
        generation: 4,
        status: "Alive",
        photo: "",
        biography:
          "Tangan kanan taktis sekaligus penyeimbang Nicholas di lapangan. Keberaniannya mengendalikan unit interceptor dalam kecepatan ekstrem menjadikannya momok menakutkan bagi para buronan kota.",
        occupation: "Police Senior Officer - High Speed Intercept Unit (LSPD)",
        father: null,
        mother: null,
        spouse: 42,
        children: [],
      },
      {
        id: 44,
        firstName: "Steven",
        lastName: "Delcano",
        gender: "male",
        generation: 4,
        status: "Deceased",
        photo: "",
        biography:
          "Memegang kendali penuh atas distrik paling korup dan peredaran narkotika. Memiliki filosofi bahwa racun di jalanan tidak bisa dimusnahkan, namun dosis dan alurnya bisa dikendalikan di bawah lencana kepolisian.",
        occupation: "Police Captain - Narcotics & Vice Division (LSPD)",
        father: 22,
        mother: 23,
        spouse: null,
        children: [],
      },
      {
        id: 45,
        firstName: "Tyan",
        lastName: "Delcano",
        gender: "male",
        generation: 4,
        status: "Deceased",
        photo: "",
        biography:
          "Komandan militer taktis berdarah dingin yang memimpin penetrasi perimeter tinggi. Percaya bahwa negosiasi terbaik dicapai ketika moncong senapan SWAT sudah mengunci dahi target operasi.",
        occupation: "Police Captain - Special Weapons & Tactics (LSPD)",
        father: 22,
        mother: 23,
        spouse: null,
        children: [],
      },
      {
        id: 46,
        firstName: "Wanzy",
        lastName: "Delcano",
        gender: "male",
        generation: 4,
        status: "Alive",
        photo: "",
        biography:
          "Melepaskan seragam dinas birokrasi demi menguasai sirkuit mekanikal kota. Menjadikan bengkelnya sebagai episentrum netral tempat bertemunya aliansi tingkat tinggi dan penyempurnaan armada taktis.",
        occupation: "Chief Executive Officer - Mechanic Customs Enterprise",
        father: 22,
        mother: 23,
        spouse: null,
        children: [],
      },
      {
        id: 47,
        firstName: "Muhafa",
        lastName: "Riverra",
        gender: "male",
        generation: 4,
        status: "Alive",
        photo: "",
        biography:
          "Inkuisitor internal korps yang bertugas memburu para pengkhianat dan polisi korup. Filosofinya kaku: 'Lencana di dada adalah kehormatan tertinggi; siapa yang mengotorinya wajib diseret ke sel isolasi.'",
        occupation: "Deputy Director - Human Resources Division (LSPD)",
        father: 24,
        mother: 25,
        spouse: null,
        children: [],
      },
      {
        id: 48,
        firstName: "Carlann",
        lastName: "Riverra",
        gender: "male",
        generation: 4,
        status: "Alive",
        photo: "",
        biography:
          "Mata sunyi di atas atap pencakar langit kota. Menguasai seni eliminasi jarak jauh, bertindak sebagai jangkar pelindung perimeter ring satu bagi jajaran High Command dan kepala negara.",
        occupation: "Master Marksman - SWAT Tactical Unit",
        father: 24,
        mother: 25,
        spouse: null,
        children: [],
      },
      {
        id: 49,
        firstName: "Ryussei",
        lastName: "Riverra",
        gender: "male",
        generation: 4,
        status: "Alive",
        photo: "",
        biography:
          "Penjaga otoritas internal yang mengawasi moralitas penegak hukum wilayah gurun Blaine County. Bertindak sebagai benteng etika agar wewenang lencana tidak disalahgunakan menjadi tirani jalanan.",
        occupation: "Deputy Director - Internal Affairs (Sheriff Department)",
        father: 26,
        mother: 27,
        spouse: null,
        children: [],
      },
      {
        id: 50,
        firstName: "Zelvin",
        lastName: "Riverra",
        gender: "male",
        generation: 4,
        status: "Alive",
        photo: "",
        biography:
          "Mata elang udara yang memetakan pola pelarian kriminal dari helikopter taktis. Baginya, dari ketinggian ribuan kaki, seluruh kota Los Santos hanyalah papan catur yang mudah dibaca.",
        occupation: "Deputy Commander - Air Support Division (LSPD)",
        father: 26,
        mother: 27,
        spouse: null,
        children: [],
      },
      {
        id: 51,
        firstName: "Kanzsu M.",
        lastName: "Riverra",
        gender: "male",
        generation: 4,
        status: "Alive",
        photo: "",
        biography:
          "Spesialis pengejaran taktis berkecepatan tinggi yang merumuskan metode penutupan barikade jalanan secara matematis. Mengubah seni berkendara interseptor menjadi sains penangkapan.",
        occupation: "Lead Specialist - High Speed Intercept Division (LSPD)",
        father: 28,
        mother: 29,
        spouse: null,
        children: [],
      },
      {
        id: 52,
        firstName: "Kenzo",
        lastName: "Riverra",
        gender: "male",
        generation: 4,
        status: "Alive",
        photo: "",
        biography:
          "Pakar medis trauma klinis yang bertarung melawan detik-detik kematian di ruang operasi darurat. Memandang tubuh manusia sebagai mesin organik rumit yang wajib diselamatkan dari kepunahan.",
        occupation: "Senior Specialist Physician - Medical Department (EMS)",
        father: 28,
        mother: 29,
        spouse: null,
        children: [],
      },
      {
        id: 53,
        firstName: "Nakamura",
        lastName: "Riverra",
        gender: "male",
        generation: 4,
        status: "Alive",
        photo: "",
        biography:
          "Penyidik siber yang meretas jaringan enkripsi rahasia milik sindikat gelap. Baginya, jejak digital adalah hantu yang mustahil dihapus sepenuhnya dari server San Andreas.",
        occupation: "Chief Specialist - Government Cyber Forensic Division",
        father: 28,
        mother: 29,
        spouse: null,
        children: [],
      },
      {
        id: 54,
        firstName: "Lucas D",
        lastName: "Riverra",
        gender: "male",
        generation: 4,
        status: "Alive",
        photo: "assets/member/lucas.png",
        biography:
          "Perwira tinggi kepolisian yang memegang kendali operasional distrik pusat. Menyeimbangkan stabilitas faksi sipil dengan ketegasan instruksi lencana hukum.",
        occupation: "Police Captain - District Operational Division (LSPD)",
        father: 30,
        mother: 31,
        spouse: null,
        children: [],
      },
      {
        id: 55,
        firstName: "Vinz M",
        lastName: "Riverra",
        gender: "male",
        generation: 4,
        status: "Alive",
        photo: "",
        biography:
          "Kadet muda yang merangkak dari dasar akademi penegak hukum. Menanggung beban berat ekspektasi nama besar keluarga di pundaknya saat menjalani indoktrinasi disiplin ketat.",
        occupation: "Police Cadet - LSPD Training Academy",
        father: 30,
        mother: 31,
        spouse: null,
        children: [],
      },
      {
        id: 56,
        firstName: "Devano",
        lastName: "Riverra",
        gender: "male",
        generation: 4,
        status: "Alive",
        photo: "",
        biography:
          "Garda terdepan penyelamatan medis lapangan yang terbiasa menantang bahaya di episentrum konflik demi memberikan pertolongan pertama pada korban kritis.",
        occupation: "Field Emergency Paramedic - Medical Services (EMS)",
        father: 30,
        mother: 31,
        spouse: null,
        children: [],
      },
      {
        id: 57,
        firstName: "Joni",
        lastName: "Riverra",
        gender: "male",
        generation: 4,
        status: "Alive",
        photo: "",
        biography:
          "Komandan taktis lapangan yang memimpin mobilisasi unit patroli reguler kota. Menjaga ritme keamanan sirkulasi harian Los Santos dari potensi anarki sipil.",
        occupation: "Deputy Commander - Tactical Patrol Operations (LSPD)",
        father: 30,
        mother: 31,
        spouse: null,
        children: [],
      },
      {
        id: 58,
        firstName: "Tommy",
        lastName: "Riverra",
        gender: "male",
        generation: 4,
        status: "Alive",
        photo: "",
        biography:
          "Penjaga hukum teritorial wilayah luar yang bertindak sebagai hakim tunggal di aspal gersang Sandy Shores, disegani karena ketegasannya mengejar pelanggar batas hukum.",
        occupation: "County Deputy Sheriff - Patrol Operations (BCSO)",
        father: 30,
        mother: 31,
        spouse: null,
        children: [],
      },
      {
        id: 59,
        firstName: "Rafael",
        lastName: "Riverra",
        gender: "male",
        generation: 4,
        status: "Alive",
        photo: "",
        biography:
          "Komandan tertinggi divisi aviasi kepolisian yang mengontrol keamanan wilayah udara San Andreas. Mengoordinasikan taktik penyergapan vertikal terpadu dari kokpit helikopter.",
        occupation: "Police Captain - Air Support Division High Command (LSPD)",
        father: 30,
        mother: 31,
        spouse: null,
        children: [],
      },
      {
        id: 60,
        firstName: "Dongsu D",
        lastName: "Riverra",
        gender: "male",
        generation: 4,
        status: "Deceased",
        photo: "",
        biography:
          "Kepala barisan pembela publik bentukan negara. Berjuang di ruang sidang demi menegakkan hak-hak konstitusional warga sipil yang tertindas oleh arogansi hukum kaum elite.",
        occupation: "Chief Captain - Public Defender Office",
        father: 30,
        mother: 31,
        spouse: null,
        children: [],
      },
      {
        id: 61,
        firstName: "Tevent",
        lastName: "Riverra",
        gender: "male",
        generation: 4,
        status: "Alive",
        photo: "",
        biography:
          "Wakil komandan unit patroli udara kepolisian yang ahli dalam manuver taktis tak terduga serta koordinasi pengeboman cahaya suar malam (flare) saat operasi malam hari.",
        occupation: "Vice Commander - Air Support Division (LSPD)",
        father: 30,
        mother: 31,
        spouse: null,
        children: [],
      },
      {
        id: 62,
        firstName: "Denis",
        lastName: "Riverra",
        gender: "male",
        generation: 4,
        status: "Alive",
        photo: "",
        biography:
          "Bintara senior kepolisian yang memegang kendali kedisiplinan barisan patroli sektor bawah. Memastikan instruksi komando tinggi terlaksana tanpa cela di lapangan.",
        occupation: "Police Sergeant I - Field Patrol Division (LSPD)",
        father: 30,
        mother: 31,
        spouse: null,
        children: [],
      },
      {
        id: 63,
        firstName: "Gogon",
        lastName: "Riverra",
        gender: "male",
        generation: 4,
        status: "Alive",
        photo: "",
        biography:
          "Sersan taktis kepolisian yang mengomandoi barisan penutupan perimeter ring dalam saat terjadi pembobolan brankas bank utama kota.",
        occupation: "Police Sergeant II - Tactical Response Unit (LSPD)",
        father: 30,
        mother: 31,
        spouse: null,
        children: [],
      },
      {
        id: 64,
        firstName: "Celcius A",
        lastName: "Riverra",
        gender: "male",
        generation: 4,
        status: "Alive",
        photo: "",
        biography:
          "Kepala investigasi internal korps yang mengawasi penyalahgunaan wewenang dan korupsi kerah putih di tubuh institusi kepolisian teratas.",
        occupation: "Police Captain - Internal Affairs Division Command (LSPD)",
        father: 30,
        mother: 31,
        spouse: null,
        children: [],
      },
      {
        id: 65,
        firstName: "Noven B",
        lastName: "Riverra",
        gender: "male",
        generation: 4,
        status: "Alive",
        photo: "",
        biography:
          "Penasihat legal divisi pengawas internal yang memproses sanksi pemberhentian tidak hormat bagi aparat hitam. Menghukum pengkhianat lewat prosedur hukum formal.",
        occupation: "Vice Commander - Legal Counsel Internal Affairs (LSPD)",
        father: 30,
        mother: 31,
        spouse: null,
        children: [],
      },
      {
        id: 66,
        firstName: "Anderson K",
        lastName: "Riverra",
        gender: "male",
        generation: 4,
        status: "Alive",
        photo: "",
        biography:
          "Petugas patroli pemula yang baru saja merampungkan masa orientasi berat lapangan. Menaruh dedikasi penuh di setiap sudut penanganan laporan kriminal perdana.",
        occupation: "Police Officer I - Rookie Probation (LSPD)",
        father: 30,
        mother: 31,
        spouse: null,
        children: [],
      },
      {
        id: 67,
        firstName: "Saeza",
        lastName: "Riverra",
        gender: "male",
        generation: 4,
        status: "Alive",
        photo: "",
        biography:
          "Pimpinan regu penyerangan taktis unit interseptor yang mendesain pola penghentian paksa kendaraan buronan bersenjata berat di jalan tol utama.",
        occupation: "Police Sergeant I - High Speed Intercept Unit (LSPD)",
        father: 30,
        mother: 31,
        spouse: null,
        children: [],
      },
      {
        id: 68,
        firstName: "Thomas",
        lastName: "Riverra",
        gender: "male",
        generation: 4,
        status: "Alive",
        photo: "",
        biography:
          "Petugas patroli madya yang menguasai teknik negosiasi krisis di lapangan, bertindak sebagai penengah taktis saat terjadi penyanderaan warga sipil.",
        occupation: "Police Officer II - Metro Patrol Division (LSPD)",
        father: 30,
        mother: 31,
        spouse: null,
        children: [],
      },
      {
        id: 69,
        firstName: "Sierra K",
        lastName: "Riverra",
        gender: "female",
        generation: 4,
        status: "Alive",
        photo: "",
        biography:
          "Satu-satunya pewaris yang memilih membalik punggungnya dari lencana penegak hukum. Meniti takdir gelap di dalam sindikat radikal Jeruzalem, memegang prinsip bahwa keadilan sejati justru lahir dari anarki total.",
        occupation: "Operative Member - Jeruzalem Syndicate (Badside)",
        father: 30,
        mother: 31,
        spouse: 70,
        children: [],
      },
      {
        id: 70,
        firstName: "Jayden",
        lastName: "Law",
        gender: "male",
        generation: 4,
        status: "Alive",
        photo: "",
        biography:
          "Satu-satunya pewaris yang memilih membalik punggungnya dari lencana penegak hukum. Meniti takdir gelap di dalam sindikat radikal Jeruzalem, memegang prinsip bahwa keadilan sejati justru lahir dari anarki total.",
        occupation: "Operative Member - Jeruzalem Syndicate (Badside)",
        father: null,
        mother: null,
        spouse: 69,
        children: [],
      },
      {
        id: 71,
        firstName: "Dinda C",
        lastName: "Riverra",
        gender: "female",
        generation: 4,
        status: "Alive",
        photo: "",
        biography:
          "Polisi wanita muda yang bertekad membuktikan kekuatannya di unit respons cepat LSPD, menolak tunduk pada dominasi maskulin di dalam korps penegak hukum.",
        occupation: "Police Officer I - Rookie Probation (LSPD)",
        father: 30,
        mother: 31,
        spouse: null,
        children: [],
      },
      {
        id: 72,
        firstName: "Luciana",
        lastName: "Riverra",
        gender: "female",
        generation: 4,
        status: "Alive",
        photo: "",
        biography:
          "Perwira patroli senior yang menguasai pemetaan taktis wilayah rawan kriminalitas urban, disegani karena ketepatan instingnya saat melakukan penangkapan.",
        occupation: "Police Officer III - Field Training Officer (LSPD)",
        father: 30,
        mother: 31,
        spouse: null,
        children: [],
      },
      {
        id: 73,
        firstName: "Yere D",
        lastName: "Riverra",
        gender: "male",
        generation: 4,
        status: "Alive",
        photo: "",
        biography: "Perwira tangguh pengawal kehormatan keluarga Riverra.",
        occupation: "Family Executive Officer",
        father: 32, // Anak dari Matteo
        mother: 33,
        spouse: 74, // Ellie Riverra
        children: [80, 81],
      },
      {
        id: 74,
        firstName: "Ellie",
        lastName: "Miles",
        gender: "female",
        generation: 4,
        status: "Alive",
        photo: "",
        biography:
          "Pendamping setia Yere D Riverra dalam menjaga stabilitas internal keluarga.",
        occupation: "House of Riverra",
        father: null,
        mother: null,
        spouse: 73,
        children: [80, 81],
      },
      {
        id: 75,
        firstName: "Simba",
        lastName: "Riverra",
        gender: "male",
        generation: 4,
        status: "Alive",
        photo: "",
        biography:
          "Sosok pelindung garis depan yang disegani di jalanan Los Santos.",
        occupation: "Tactical Specialist",
        father: 32, // Anak dari Matteo
        mother: 33,
        spouse: null,
        children: [82, 83, 84],
      },
      {
        id: 76,
        firstName: "Vincent M",
        lastName: "Riverra",
        gender: "male",
        generation: 4,
        status: "Alive",
        photo: "",
        biography:
          "Darah muda bertalenta tinggi yang meniti karier penegakan hukum dari dasar korps.",
        occupation: "Police Cadet - LSPD Training Academy",
        father: 32, // Anak dari Matteo
        mother: 33,
        spouse: null,
        children: [],
      },
      {
        id: 77,
        firstName: "Cassio",
        lastName: "Riverra",
        gender: "male",
        generation: 5,
        status: "Alive",
        photo: "",
        biography:
          "Warga sipil yang dikenal bijaksana dan rendah hati. Memegang teguh nilai kekeluargaan serta selalu berusaha menjaga kehormatan nama besar keluarga Riverra.",
        occupation: "Civilian",
        father: 34,
        mother: 35,
        spouse: null,
        children: [],
      },
      {
        id: 78,
        firstName: "Ferris H",
        lastName: "Riverra",
        gender: "male",
        generation: 5,
        status: "Alive",
        photo: "",
        biography:
          "Perwira senior kepolisian yang mengemban tanggung jawab besar dalam memimpin operasional dan pembinaan personel. Dikenal sebagai sosok berintegritas tinggi yang mengutamakan profesionalisme serta pengabdian kepada masyarakat.",
        occupation: "Assistant Chief of Police",
        father: 34,
        mother: 35,
        spouse: null,
        children: [],
      },
      {
        id: 79,
        firstName: "Abbrilla",
        lastName: "Riverra",
        gender: "female",
        generation: 5,
        status: "Alive",
        photo: "",
        biography:
          "Warga sipil yang memiliki kepribadian hangat dan peduli terhadap sesama. Berkomitmen menjaga nilai-nilai yang telah diwariskan oleh keluarga Riverra kepada generasi berikutnya.",
        occupation: "Civilian",
        father: 34,
        mother: 35,
        spouse: null,
        children: [],
      },
      {
        id: 80,
        firstName: "Moraira",
        lastName: "Riverra",
        gender: "male",
        generation: 5,
        status: "Alive",
        photo: "",
        biography:
          "Mahasiswa yang memiliki ketertarikan pada kebijakan publik dan kepemimpinan. Dikenal tenang dalam mengambil keputusan serta aktif mengikuti berbagai kegiatan organisasi kampus.",
        occupation: "University Student",
        father: 73,
        mother: 74,
        spouse: null,
        children: [],
      },
      {
        id: 81,
        firstName: "Valenciana",
        lastName: "Riverra",
        gender: "female",
        generation: 5,
        status: "Alive",
        photo: "",
        biography:
          "Mahasiswi yang tumbuh dengan menjunjung tinggi nilai kekeluargaan. Memiliki minat pada kegiatan sosial dan sering terlibat dalam program pengabdian masyarakat.",
        occupation: "University Student",
        father: 73,
        mother: 74,
        spouse: null,
        children: [],
      },
      {
        id: 82,
        firstName: "Declan Malaka",
        lastName: "Riverra",
        gender: "male",
        generation: 5,
        status: "Alive",
        photo: "",
        biography:
          "Perwira muda yang dikenal disiplin dan sigap dalam menjalankan tugas. Bertekad menjaga nama baik keluarga Riverra melalui dedikasi dan integritas sebagai penegak hukum.",
        occupation: "Police Officer",
        father: 75,
        mother: null,
        spouse: null,
        children: [],
      },
      {
        id: 83,
        firstName: "Lumut Bersyukur",
        lastName: "Riverra",
        gender: "male",
        generation: 5,
        status: "Alive",
        photo: "",
        biography:
          "Warga sipil yang lebih memilih kehidupan sederhana. Dikenal rendah hati dan selalu mengutamakan persatuan serta keharmonisan dalam keluarga.",
        occupation: "Civilian",
        father: 75,
        mother: null,
        spouse: null,
        children: [],
      },
      {
        id: 84,
        firstName: "James",
        lastName: "Riverra",
        gender: "male",
        generation: 5,
        status: "Alive",
        photo: "",
        biography:
          "Mahasiswa yang memiliki ketertarikan pada teknologi dan inovasi. Dipandang sebagai sosok yang cepat beradaptasi dengan perkembangan zaman.",
        occupation: "University Student",
        father: 75,
        mother: null,
        spouse: null,
        children: [],
      },
      {
        id: 85,
        firstName: "Kevinn D",
        lastName: "Riverra",
        gender: "male",
        generation: 5,
        status: "Alive",
        photo: "",
        biography:
          "Mahasiswa yang aktif mengikuti organisasi kampus dan kegiatan kepemudaan. Memiliki jiwa kepemimpinan yang mulai terlihat sejak usia muda.",
        occupation: "University Student",
        father: 76,
        mother: null,
        spouse: null,
        children: [],
      },
      {
        id: 86,
        firstName: "Takeshi",
        lastName: "Riverra",
        gender: "male",
        generation: 5,
        status: "Alive",
        photo: "",
        biography:
          "Keturunan berdarah campuran yang dikenal disiplin dan menghargai budaya dari kedua sisi keluarganya. Sedang menempuh pendidikan tinggi sambil mengembangkan kemampuan diri.",
        occupation: "University Student",
        father: 76,
        mother: null,
        spouse: null,
        children: [],
      },
      {
        id: 87,
        firstName: "Aiden",
        lastName: "Riverra",
        gender: "male",
        generation: 5,
        status: "Alive",
        photo: "",
        biography:
          "Warga sipil yang dikenal ramah dan mudah bergaul. Menjadi salah satu generasi muda Riverra yang berusaha menjaga reputasi keluarga melalui tindakan positif dalam kehidupan sehari-hari.",
        occupation: "Civilian",
        father: 76,
        mother: null,
        spouse: null,
        children: [],
      },
      {
        id: 88,
        firstName: "El Kun S",
        lastName: "Riverra",
        gender: "male",
        generation: 5,
        status: "Alive",
        photo: "",
        biography:
          "Warga sipil yang dikenal ramah dan mudah bergaul. Menjalani kehidupan sederhana sambil menjaga nama baik keluarga Riverra.",
        occupation: "Civilian",
        father: 54,
        mother: null,
        spouse: null,
        children: [],
      },
      {
        id: 89,
        firstName: "Ujang R",
        lastName: "Riverra",
        gender: "male",
        generation: 5,
        status: "Alive",
        photo: "",
        biography:
          "Warga sipil yang memiliki semangat kerja keras dan selalu mengutamakan rasa kekeluargaan dalam kehidupan sehari-hari.",
        occupation: "Civilian",
        father: 54,
        mother: null,
        spouse: null,
        children: [],
      },
      {
        id: 90,
        firstName: "Zeyy",
        lastName: "Riverra",
        gender: "male",
        generation: 5,
        status: "Alive",
        photo: "",
        biography:
          "Warga sipil yang tenang dan mudah beradaptasi. Dikenal sebagai pribadi yang menghargai persahabatan dan loyalitas.",
        occupation: "Civilian",
        father: 54,
        mother: null,
        spouse: null,
        children: [],
      },
      {
        id: 91,
        firstName: "Alger",
        lastName: "Riverra",
        gender: "male",
        generation: 5,
        status: "Alive",
        photo: "",
        biography:
          "Warga sipil yang menjunjung tinggi tanggung jawab serta selalu berusaha memberikan dampak positif bagi lingkungan sekitarnya.",
        occupation: "Civilian",
        father: 54,
        mother: null,
        spouse: null,
        children: [],
      },
      {
        id: 92,
        firstName: "Shin Y",
        lastName: "Riverra",
        gender: "male",
        generation: 5,
        status: "Alive",
        photo: "",
        biography:
          "Mekanik di Kerta Garage yang dikenal teliti dan berdedikasi tinggi dalam menangani setiap kendaraan pelanggan.",
        occupation: "Mechanic - Kerta Garage",
        father: 54,
        mother: null,
        spouse: null,
        children: [],
      },
      {
        id: 93,
        firstName: "Ester",
        lastName: "Riverra",
        gender: "female",
        generation: 5,
        status: "Alive",
        photo: "",
        biography:
          "Paramedis Roxwood Hospital yang mengabdikan dirinya untuk memberikan pelayanan medis terbaik dengan penuh empati dan profesionalisme.",
        occupation: "Paramedic - Roxwood Hospital",
        father: 54,
        mother: null,
        spouse: null,
        children: [],
      },
      {
        id: 94,
        firstName: "Marine H",
        lastName: "Riverra",
        gender: "female",
        generation: 5,
        status: "Alive",
        photo: "",
        biography:
          "Mahasiswi yang aktif mengembangkan kemampuan akademik sekaligus menjaga nilai-nilai yang diwariskan keluarga Riverra.",
        occupation: "University Student",
        father: 54,
        mother: null,
        spouse: null,
        children: [],
      },
      {
        id: 95,
        firstName: "Aang",
        lastName: "Riverra",
        gender: "male",
        generation: 5,
        status: "Alive",
        photo: "",
        biography:
          "Mekanik di Kerta Garage yang dikenal cekatan dan selalu mengutamakan kualitas dalam setiap pekerjaannya.",
        occupation: "Mechanic - Kerta Garage",
        father: 54,
        mother: null,
        spouse: null,
        children: [],
      },
      {
        id: 96,
        firstName: "Gracie N",
        lastName: "Riverra",
        gender: "female",
        generation: 5,
        status: "Alive",
        photo: "",
        biography:
          "Mahasiswi yang aktif mengikuti berbagai kegiatan kampus serta memiliki semangat tinggi untuk terus berkembang dan mengharumkan nama keluarga.",
        occupation: "University Student",
        father: 54,
        mother: null,
        spouse: null,
        children: [],
      },
      {
        id: 97,
        firstName: "Pyolilo El C",
        lastName: "Riverra",
        gender: "male",
        generation: 5,
        status: "Alive",
        photo: "",
        biography:
          "Perwira kepolisian yang dikenal disiplin, tegas, dan berdedikasi tinggi dalam menjaga keamanan masyarakat. Menjalankan tugas dengan menjunjung tinggi integritas serta kehormatan keluarga Riverra.",
        occupation: "Police Officer III",
        father: 61,
        mother: null,
        spouse: null,
        children: [],
      },
      {
        id: 98,
        firstName: "Yumeira",
        lastName: "Riverra",
        gender: "female",
        generation: 5,
        status: "Alive",
        photo: "",
        biography:
          "Warga sipil yang dikenal ramah dan memiliki kepedulian tinggi terhadap keluarga. Selalu berusaha menjaga nama baik dinasti Riverra melalui sikap yang rendah hati dan penuh tanggung jawab.",
        occupation: "Civilian",
        father: 61,
        mother: null,
        spouse: null,
        children: [],
      },
];

// Wadah kamus pelacak ID (ID_LAMA : ID_BARU)
const idMap = {};

async function startMigration() {
  console.log("=== MEMULAI MIGRASI DATA SILSILAH RIVERRA ===");

  // Urutkan data berdasarkan generasi (Generasi 1 masuk paling awal)
  const sortedData = [...familyData].sort((a, b) => a.generation - b.generation);

  for (const member of sortedData) {
    try {
      // Terjemahkan relasi ID orang tua lama ke ID baru menggunakan Kamus idMap
      const fatherIdNew = member.father ? idMap[member.father] || null : null;
      const motherIdNew = member.mother ? idMap[member.mother] || null : null;

      // Catatan: Relasi pasangan (spouse_id) akan di-update di tahap kedua 
      // karena saat suami di-insert, data istri mungkin belum masuk database.

      const { data: insertedMember, error } = await supabase
        .from('members')
        .insert([{
          first_name: member.firstName,
          last_name: member.lastName,
          gender: member.gender,
          generation: member.generation,
          status: member.status,
          photo: member.photo,
          biography: member.biography,
          occupation: member.occupation,
          role: member.role || '',
          father_id: fatherIdNew,
          mother_id: motherIdNew,
          spouse_id: null // Set kosong dulu sementara waktu
        }])
        .select('id')
        .single();

      if (error) {
        console.error(`❌ Gagal menyimpan ${member.firstName}:`, error.message);
        continue;
      }

      // Kunci Utama: Simpan konversi ID lama ke ID unik baru dari Supabase
      idMap[member.id] = insertedMember.id;
      console.log(`✅ Berhasil import: ${member.firstName} ${member.lastName} (ID Lama: ${member.id} -> ID Baru: ${insertedMember.id})`);

    } catch (err) {
      console.error("Terjadi error tak terduga:", err);
    }
  }

  console.log("\n=== TAHAP 2: MENYINKRONKAN DATA RELASI PASANGAN (SPOUSE ID) ===");

  for (const member of sortedData) {
    if (member.spouse) {
      const currentNewId = idMap[member.id];
      const spouseNewId = idMap[member.spouse];

      if (currentNewId && spouseNewId) {
        const { error } = await supabase
          .from('members')
          .update({ spouse_id: spouseNewId })
          .eq('id', currentNewId);

        if (error) {
          console.error(`❌ Gagal update pasangan untuk ID Baru ${currentNewId}:`, error.message);
        } else {
          console.log(`🔗 Relasi tersambung: ID Baru ${currentNewId} berpasangan dengan ID Baru ${spouseNewId}`);
        }
      }
    }
  }

  console.log("\n🎉 MIGRSI SELESAI SEMPURNA! Seluruh data terhubung dengan ID Unik Baru.");
}

startMigration();