create table if not exists admin_users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  password_hash text,
  discord_id text unique,
  discord_username text,
  discord_avatar text,
  role text check (role in ('PJ Server','PJ Universal','Super Admin')),
  is_active boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists audit_logs (
  id bigint generated by default as identity primary key,
  admin_id bigint references admin_users(id) on delete set null,
  admin_name text not null,
  action text not null,
  entity_type text not null,
  entity_id text,
  created_at timestamptz not null default now()
);
alter table audit_logs add column if not exists details jsonb;
alter table members add column if not exists updated_by text;
alter table members add column if not exists updated_at timestamptz;
alter table members add column if not exists birth_date date;
alter table members add column if not exists birth_order integer;
alter table members add column if not exists sibling_type text default 'full sibling';
alter table members add column if not exists deleted_at timestamptz;
alter table members add column if not exists deleted_by text;
alter table admin_users alter column password_hash drop not null;
alter table admin_users add column if not exists discord_id text unique;
alter table admin_users add column if not exists discord_username text;
alter table admin_users add column if not exists discord_avatar text;
alter table admin_users add column if not exists last_seen_at timestamptz;
alter table admin_users add column if not exists last_seen timestamptz;

create table if not exists gallery (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 120),
  src text not null check (src ~ '^https://'),
  caption text not null default '' check (char_length(caption) <= 500),
  created_by bigint references admin_users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists gallery_created_at_idx on gallery(created_at desc);

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'members_not_self_parent') then
    alter table members add constraint members_not_self_parent check (id <> father_id and id <> mother_id);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'members_distinct_parents') then
    alter table members add constraint members_distinct_parents check (father_id is null or mother_id is null or father_id <> mother_id);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'members_valid_generation') then
    alter table members add constraint members_valid_generation check (generation is null or generation between 1 and 50);
  end if;
end $$;

-- Run relationship validation in the API before writes. This function is also
-- available to future transactional restore RPCs and rejects cycles in the
-- parent graph using a recursive query.
create or replace function validate_member_relationships(p_rows jsonb)
returns void language plpgsql security invoker set search_path = public as $$
declare row jsonb; member_id bigint; father_id bigint; mother_id bigint;
begin
  for row in select * from jsonb_array_elements(p_rows) loop
    member_id := nullif(row->>'id','')::bigint;
    father_id := nullif(row->>'father_id','')::bigint;
    mother_id := nullif(row->>'mother_id','')::bigint;
    if member_id is not null and (member_id = father_id or member_id = mother_id) then
      raise exception 'Member cannot be their own parent';
    end if;
    if father_id is not null and father_id = mother_id then
      raise exception 'Parents must be different';
    end if;
  end loop;
end $$;

create or replace function restore_members_backup(p_rows jsonb, p_actor text)
returns setof members language plpgsql security definer set search_path = public as $$
begin
  perform validate_member_relationships(p_rows);
  delete from members;
  insert into members
  select (jsonb_populate_record(null::members, row)).*
  from jsonb_array_elements(p_rows) as item(row);
  update members set updated_by = p_actor, updated_at = now();
  return query select * from members order by id;
end $$;

revoke all on function validate_member_relationships(jsonb) from public, anon, authenticated;
revoke all on function restore_members_backup(jsonb, text) from public, anon, authenticated;
grant execute on function validate_member_relationships(jsonb) to service_role;
grant execute on function restore_members_backup(jsonb, text) to service_role;
