create table if not exists admin_users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  password_hash text,
  discord_id text unique,
  discord_username text,
  discord_avatar text,
  role text check (role in ('PJ Server','PJ Universal','Super Admin')),
  is_active boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists audit_logs (
  id bigint generated by default as identity primary key,
  admin_id bigint references admin_users(id) on delete set null,
  admin_name text not null,
  action text not null,
  entity_type text not null,
  entity_id text,
  created_at timestamptz not null default now()
);
alter table audit_logs add column if not exists details jsonb;
alter table members add column if not exists updated_by text;
alter table members add column if not exists updated_at timestamptz;
alter table members add column if not exists birth_date date;
alter table members add column if not exists birth_order integer;
alter table members add column if not exists sibling_type text default 'full sibling';
alter table members add column if not exists deleted_at timestamptz;
alter table members add column if not exists deleted_by text;
alter table admin_users alter column password_hash drop not null;
alter table admin_users add column if not exists discord_id text unique;
alter table admin_users add column if not exists discord_username text;
alter table admin_users add column if not exists discord_avatar text;
alter table admin_users add column if not exists last_seen_at timestamptz;
alter table admin_users add column if not exists last_seen timestamptz;
