create table if not exists admin_users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  password_hash text not null,
  role text check (role in ('PJ Server','PJ Universal','Super Admin')),
  is_active boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists audit_logs (
  id bigint generated by default as identity primary key,
  admin_id bigint references admin_users(id) on delete set null,
  admin_name text not null,
  action text not null,
  entity_type text not null,
  entity_id text,
  created_at timestamptz not null default now()
);
alter table members add column if not exists updated_by text;
alter table members add column if not exists updated_at timestamptz;
